// scripts/fetchNotionData.mjs
// Fetches photo data from Notion DB at build time.
// Requires environment variables:
//   NOTION_TOKEN          — Notion Internal Integration Secret
//   NOTION_PHOTO_DB_ID    — (optional) Notion photo database ID

import { Client } from '@notionhq/client';
import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const NOTION_TOKEN = process.env.NOTION_TOKEN;
if (!NOTION_TOKEN) {
  console.error('Error: NOTION_TOKEN environment variable is not set.');
  process.exit(1);
}

// This DB ID is specific to this project and safe to include as a default.
const PHOTO_DB_ID =
  process.env.NOTION_PHOTO_DB_ID ?? '334fb4c819b38038ad45e080de3073a0';

const PHOTOS_DIR = join(__dirname, '../public/haru/photos');

const notion = new Client({ auth: NOTION_TOKEN });

/** Download a remote file and save it to disk, skipping if already present. */
async function downloadFile(url, filepath) {
  if (existsSync(filepath)) {
    console.log(`  Skipping (already exists): ${filepath}`);
    return;
  }
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: ${res.statusText}`);
  const buffer = await res.arrayBuffer();
  writeFileSync(filepath, Buffer.from(buffer));
}

/** Extract the file extension from a URL path, defaulting to 'jpg'. */
function extractExt(url) {
  try {
    const pathname = new URL(url).pathname;
    const ext = pathname.split('.').pop()?.toLowerCase() ?? '';
    return ['jpg', 'jpeg', 'png', 'gif', 'webp'].includes(ext) ? ext : 'jpg';
  } catch {
    return 'jpg';
  }
}

async function fetchAllPages(databaseId) {
  const pages = [];
  let cursor = undefined;
  do {
    const res = await notion.dataSources.query({
      data_source_id: databaseId,
      start_cursor: cursor,
      page_size: 100,
    });
    pages.push(...res.results);
    cursor = res.has_more ? res.next_cursor : undefined;
  } while (cursor);
  return pages;
}

async function processPage(page) {
  // Extract caption property (rich_text type)
  const captionProp = page.properties?.caption ?? page.properties?.Caption;
  let caption = '';
  if (captionProp?.type === 'rich_text' && captionProp.rich_text.length > 0) {
    caption = captionProp.rich_text.map((t) => t.plain_text).join('');
  }

  // Find the first image block in the page body
  let imageUrl = null;
  let blockCursor = undefined;
  outer: do {
    const blocks = await notion.blocks.children.list({
      block_id: page.id,
      start_cursor: blockCursor,
      page_size: 100,
    });
    for (const block of blocks.results) {
      if (block.type === 'image') {
        const img = block.image;
        imageUrl =
          img.type === 'file' ? img.file.url : (img.external?.url ?? null);
        break outer;
      }
    }
    blockCursor = blocks.has_more ? blocks.next_cursor : undefined;
  } while (blockCursor);

  if (!imageUrl) {
    console.warn(`Page ${page.id}: no image found, skipping.`);
    return null;
  }

  const ext = extractExt(imageUrl);
  const filename = `photo_${page.id.replace(/-/g, '')}.${ext}`;
  const filepath = join(PHOTOS_DIR, filename);

  console.log(`Downloading: ${filename}`);
  await downloadFile(imageUrl, filepath);

  return {
    id: page.id,
    filename,
    alt: caption || '하루',
    ...(caption ? { caption } : {}),
  };
}

async function fetchPhotos() {
  mkdirSync(PHOTOS_DIR, { recursive: true });

  const pages = await fetchAllPages(PHOTO_DB_ID);
  console.log(`Found ${pages.length} pages in Notion DB.`);

  // Process pages in parallel with a concurrency limit of 5
  const CONCURRENCY = 5;
  const results = [];
  for (let i = 0; i < pages.length; i += CONCURRENCY) {
    const batch = pages.slice(i, i + CONCURRENCY);
    const batchResults = await Promise.all(batch.map(processPage));
    results.push(...batchResults);
  }

  return results.filter(Boolean);
}

async function main() {
  console.log('Fetching photos from Notion\u2026');
  const photos = await fetchPhotos();
  console.log(`Generated ${photos.length} photo entries.`);

  const mediaDataPath = join(__dirname, '../src/data/mediaData.ts');
  const content = `// Auto-generated by scripts/fetchNotionData.mjs \u2014 do not edit manually

export interface Photo {
  id: string;
  filename: string;
  alt: string;
  caption?: string;
}

export const photos: Photo[] = ${JSON.stringify(photos, null, 2)};

export interface Video {
  id: string;
  filename: string;
  title: string;
  caption?: string;
}

export const videos: Video[] = [];
`;

  writeFileSync(mediaDataPath, content, 'utf-8');
  console.log('Wrote src/data/mediaData.ts');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
